keyMirror = require 'keymirror'

module.exports = keyMirror

  GET_ARIA_DATA: 'GET_ARIA_DATA'
  ARIA_DATA_LOADED: 'ARIA_DATA_LOADED'
  ARIA_DATA_ERROR: 'ARIA_DATA_ERROR'
  TOGGLE_EXPANDER: 'TOGGLE_EXPANDER'
  SELECT_ATTRIBUTE: 'SELECT_ATTRIBUTE'
  TOGGLE_MINIMIZER: 'TOGGLE_MINIMIZER'
